from . import test_easyocr_bill
from . import test_easyocr_batch
from . import test_easyocr_document
from . import test_easyocr_expense
from . import test_easyocr_expense_target
from . import test_easyocr_extractor
from . import test_easyocr_home
from . import test_easyocr_icons
from . import test_easyocr_inbox
from . import test_easyocr_lines
from . import test_easyocr_settings
from . import test_easyocr_template
from . import test_easyocr_upload
from . import test_easyocr_translations
from . import test_easyocr_webhook
from . import test_easyocr_webhook_payment
